[package]
name = "hash_cracker"
version = "0.1.0"
edition = "2021"
authors = ["Mehrnoush"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha-1 = "0.10"
hex = "0.4"
sha2 = "0.10"
md5 = "0.7.0"
